[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["marrow/"]

[tool.hatch.build.targets.sdist]
packages = ["marrow/"]

[project]
name = 'marrow.util'
version = '1.2.4+final2'
description = "A collection of many commonly reimplemented utility classes and functions."
authors = [
  { name = "Alice Bevan-McGregor", email = "alice@gothcandy.com" },
]
license = 'MIT'
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2.6",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.1",
    "Programming Language :: Python :: 3.2",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]
